### ISSUE TITLE
Problems when no values are parsed for DataIn in datasets

### ISSUE THREAD

**Issue by davide-f** [PyPSA/powerplantmatching#101]
Several datasets do have missing values especially for commissioning dates of powerplants.
In the GPD database the number of missing values is over 30k entries.

That is because the various nan fixing unfortunately fail when no data are provided at all; see https://github.com/PyPSA/powerplantmatching/blob/d9be8240971860a5df4849d9abc6e6d7a93b0e95/powerplantmatching/heuristics.py#L255

Currently and errors are thrown, but I think it is ok for European use that is unlikely to happen but in Africa that is a problem.
Could we add a warning instead of an error and hard code a date; eventually a date equals 0, but something that doesnt' the code crashes.

Let me know if there are suggestions on that.

**Comment by FabianHofmann** [comment]
Hey Davide, since it is not possible to convert Nans to int, we could just change the dtype of DateIn to float instead. What do you think?

**Comment by davide-f** [comment]
Nice idea!
May I include in the same idea the riformulazione to avoid the .loc[:,...] warning by pandas? Not sure if I'll address that issue though
I guess you know the point.

**Comment by FabianHofmann** [comment]
good idea!
