### ISSUE TITLE
Add data from Global Hydropower Tracker

### ISSUE THREAD

**Issue by fneum** [PyPSA/powerplantmatching#114]
https://globalenergymonitor.org/wp-content/uploads/2023/04/Global-Hydropower-Tracker-May-2023.xlsx

Follow-on for #110

**Comment by Tomkourou** [comment]
We can close this as it was already addressed in #110 here -> acee44494ccb3b38a3182da9b31bf6a8297fcb30

**Comment by FabianHofmann** [comment]
thanks @Tomkourou for pointing out
