### ISSUE TITLE
config_filter function returning NaNs for DateOut

### ISSUE THREAD

**Issue by Tomkourou** [PyPSA/powerplantmatching#119]
I am testing powerplantmatching for Indonesia. Just looking at the GEM datasets the line .pipe(config_filter,config) returns datasets where DateOut is full of NaNs despite the fact there should be data there. 

This is the line in question 
https://github.com/PyPSA/powerplantmatching/blob/97e3172b4aeabf09b42c68118c5e55a0242ffa8e/powerplantmatching/data.py#L1765
It has something to do with the config_filter function though I haven't been able to find the root cause of it yet. 

I have tested it with Egypt and Nigeria and got the same behaviour. It's possible this is happening with other columns too but I only tested it for the DateOut column.

**Comment by FabianHofmann** [comment]
Hey @Tomkourou, are you sure it does not appear in https://github.com/PyPSA/powerplantmatching/blob/97e3172b4aeabf09b42c68118c5e55a0242ffa8e/powerplantmatching/data.py#L1759 ?

**Comment by Tomkourou** [comment]
Checked in debug. the outputs until line 1765 look fine.

**Comment by Tomkourou** [comment]
Can't replicate the issue anymore. Closing this.
