### ISSUE TITLE
Use latest JRC hydro power plant data 

### ISSUE THREAD

**Issue by martinhjel** [PyPSA/powerplantmatching#122]
Hi, I have noticed that the default dataset for the JRC is v10. This dataset is, however, from 2021. Is there any reason to not use the latest dataset instead?: https://github.com/energy-modelling-toolkit/hydro-power-database/blob/master/data/jrc-hydro-power-plant-database.csv

**Comment by FabianHofmann** [comment]
Hey @martinhjel, actually the only reason is that we have not updated the version yet. You're interested in making a PR?

**Comment by martinhjel** [comment]
See #123
