### ISSUE TITLE
Facing an Import Error

### ISSUE THREAD

**Issue by dhrumit98** [PyPSA/powerplantmatching#130]
@FabianHofmann : Using **Anaconda - Python** for running the program, just installed the powerplantatching tool,
I m in the Initial phase it self, not even modified the code yet. 

**from .core import get_obj_if_Acc, [get_config**]
ImportError: attempted relative import with no known parent package

**Comment by FabianHofmann** [comment]
hey @dhrumit98, could you provide the full stack trace?

**Comment by lkstrp** [comment]
Closed due to inactivity. Please reopen if needed.
