### ISSUE TITLE
address concatenation future warning:

### ISSUE THREAD

**Issue by fneum** [PyPSA/powerplantmatching#142]
/REDACTED/python3.11/site-packages/powerplantmatching/export.py:76: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  buses_i = buses.index.append(pd.Index([np.nan]))

**Comment by lkstrp** [comment]
Done already.
