### ISSUE TITLE
Error in build_powerplants

### ISSUE THREAD

**Issue by shithikanta** [PyPSA/powerplantmatching#191]
I have seen the recent commit of changing the FRESNA but still the while running it is not using the new link and showing the error attached, I cloned the repository as on 4th Aug'24 around 9PM (for the time ref. ) , I am tried running the tutorial network config/test/config.electricity.yaml
[error details.txt](https://github.com/user-attachments/files/16488747/error.details.txt)

**Comment by lkstrp** [comment]
Linked to #192
