### ISSUE TITLE
Versioning in conda installation not consistent

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/powerplantmatching#192]
When installing the latest version with conda, the package version does not reflect the actual installed version. This leads to wrong url target in `pm.powerplants(from_url=True)`.  

Steps to reproduce

```
mamba create -n ppm "powerplantmatching==0.5.16" 

mamba activate ppm  

python

>>> import powerplantmatching as pm
>>> pm.__version__

```

This yields `0.5.5`. I also had the case where the version was "0.0.0". 

@lkstrp if you are flexible and I don't miss anything, I would give this high prio.

**Comment by lkstrp** [comment]
Closed via feedstock.

Reinstall version to fix issue. You may need to clear the cache first.
