### ISSUE TITLE
WEPP Integration is outdated

### ISSUE THREAD

**Issue by Eugenio2192** [PyPSA/powerplantmatching#42]
I tried adding the WEPP dataset but it seems that the data function is using what seems an old method; it is referencing a config that is not there "config['WEPP']['source_file']". I solved it locally by implementing the "parse_if_not_stored" function but I don´t know if that´s ideal. 
I had to use custom kwargs because when I exported the dataset in my computer it used european locale so I had to specify the separation symbols etc. Maybe include this as part of the config options? I have an example from my own project (kudos because I use yours partially) , look at the InputConfig field:

https://gitlab.com/dlr-ve/autumn/-/blob/master/autumn/config.yaml

**Comment by FabianHofmann** [comment]
hey @Eugenio2192, it's good that you could resolve it. We are not using the WEPP database anymore and @fgotzens who implemented it is also very buisy. So feel free to make a proposition in a PR.

**Comment by Eugenio2192** [comment]
Thanks for the reply, I haven't done a PR because my solution dropped its own issues so I am still working on it.

**Comment by FabianHofmann** [comment]
Closing stale issue
