### ISSUE TITLE
broken powerplantmatching.utils.fill_geoposition 

### ISSUE THREAD

**Issue by lisazeyen** [PyPSA/powerplantmatching#57]
as pointed out by @ericzhou571 [powerplantmatching.utils.fill_geoposition](https://github.com/FRESNA/powerplantmatching/blob/master/powerplantmatching/utils.py#L592) does not work anymore

Error message:
`ConfigurationError: Since July 2018 Google requires each request to have an API key. Pass a valid `api_key` to GoogleV3 geocoder to fix this error.`

See also [here](https://developers.google.com/maps/documentation/geocoding/usage-and-billing)

**Comment by FabianHofmann** [comment]
Closing, as the function is not broken but the api key seems to be missing. This has to be added to the `.powerplantmatching_config.yaml`, see https://powerplantmatching.readthedocs.io/en/latest/custom-config.html. Reopen if something is still missing.
