### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'Name

### ISSUE THREAD

**Issue by chadhat** [PyPSA/powerplantmatching#68]
Error when trying to load any data. (using e.g. pm.data.ENTSOE() or pm.powerplants() )

Example: 

import powerplantmatching as pm
entsoe = pm.data.ENTSOE()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-96155cab6740> in <module>
----> 1 entsoe = pm.data.ENTSOE()

/media/chadhat/4d105adc-3356-4a16-9761-ee0dcd7f23dc/Work/Networks/database-matching/env/lib/python3.8/site-packages/powerplantmatching/data.py in ENTSOE(raw, update, config, entsoe_token, **fill_geoposition_kwargs)
    721 
    722     return (
--> 723         df.rename_axis(index="projectID")
    724         .reset_index()
    725         .rename(columns=RENAME_COLUMNS)

/media/chadhat/4d105adc-3356-4a16-9761-ee0dcd7f23dc/Work/Networks/database-matching/env/lib/python3.8/site-packages/pandas/core/frame.py in assign(self, **kwargs)
   4484 
   4485         for k, v in kwargs.items():
-> 4486             data[k] = com.apply_if_callable(v, data)
   4487         return data
   4488 

/media/chadhat/4d105adc-3356-4a16-9761-ee0dcd7f23dc/Work/Networks/database-matching/env/lib/python3.8/site-packages/pandas/core/common.py in apply_if_callable(maybe_callable, obj, **kwargs)
    356     """
    357     if callable(maybe_callable):
--> 358         return maybe_callable(obj, **kwargs)
    359 
    360     return maybe_callable

/media/chadhat/4d105adc-3356-4a16-9761-ee0dcd7f23dc/Work/Networks/database-matching/env/lib/python3.8/site-packages/powerplantmatching/data.py in <lambda>(df)
    726         .drop_duplicates("projectID")
    727         .assign(
--> 728             Name=lambda df: df.Name.str.replace("_", " "),  # for geoparsing
    729             EIC=lambda df: df.projectID,
    730             Country=lambda df: df.projectID.str[:2].map(COUNTRY_MAP),

/media/chadhat/4d105adc-3356-4a16-9761-ee0dcd7f23dc/Work/Networks/database-matching/env/lib/python3.8/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5485         ):
   5486             return self[name]
-> 5487         return object.__getattribute__(self, name)
   5488 
   5489     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'Name'

**Comment by FabianHofmann** [comment]
Hey @chadhat I cannot not reprocude the error, which version are currently at? There were a lot of updates recently...

**Comment by chadhat** [comment]
@FabianHofmann I am using the version '0.5.3' with Python 3.8.10

**Comment by FabianHofmann** [comment]
I still cannot reproduce the error, even from a fresh install in a new environment. Do you have the ENSTSOE api key added to your config?

**Comment by C-Perez-Villanueva** [comment]
Mmm I am not sure. I have the package entsoe-py installed in its version 0.5.4, but if the api key you're saying is the one I have to request via email directly to ENTSOE, I was not aware I needed that and I just requested it. Hence, I think I have to wait to receive it to try it again.

**Comment by chadhat** [comment]
> 

How should this key be added? Shall this be added to the dictionary pm.package_config? If yes, with what key?

**Comment by C-Perez-Villanueva** [comment]
@chadhat, I think you have to modify the .powerplantmatching_config.yaml file, as written in the following page: https://github.com/FRESNA/powerplantmatching/blob/master/doc/custom-config.rst

@FabianHofmann I already added the token/api key to my configuration, but I'm still facing the same problem. I was thinking maybe to reinstall the package in a new environment, maybe there was sth wrong during the installation.

**Comment by FabianHofmann** [comment]
I hope with the new versions this issue is resolved, please reopen if not
