### ISSUE TITLE
Using powerplantmatching for a new dataset

### ISSUE THREAD

**Issue by chadhat** [PyPSA/powerplantmatching#70]
Is it possible to use powerplantmatching on a new different dataset?

We have a network dataset where some of the information such as geographical location is missing. Would it be possible to match it with the datasets already included in powerplantmatching?

If yes, what is the way to do that? Do you have some documentation for that?

**Comment by FabianHofmann** [comment]
Hey @chadhat, sorry for the late reply! There is a section is the documentation for this

https://powerplantmatching.readthedocs.io/en/latest/contributing.html#integrating-new-data-sources

Please reopen if the you need further help.
