### ISSUE TITLE
PHS capacity

### ISSUE THREAD

**Issue by ebbekyhl** [PyPSA/powerplantmatching#72]
Hi,

With regard to pumped-hydro storage (PHS), the newest version of powerplantmatching shows an existing energy storage capacity of 4.3 TWh (Europe-aggregate, assuming 6-hours duration for plants that do not have duration specified). In the earlier version 0.4.8, this number was a bit higher (10 TWh). As comparison, Geth et al. (2015) showed a PHS energy capacity of 1.3 TWh (including Norway and Switzerland) using 2012-numbers. PHS power capacity has increased from roughly 50 to 55 GW from 2014 to 2020 (iha, 2015, 2021), so energy storage capacity most likely is increased as well. But is it fair to say that energy storage capacity has been almost quadrupled since 2012 (from 1.3 TWh to 4.3 TWh)? Or how can we interpret this discrepancy? 

Looking forward to hearing from you.

Sources:
Geth et al., 2015, https://doi.org/10.1016/j.rser.2015.07.145
iha, 2015, https://www.aler-renovaveis.org/contents/lerpublication/iha_2015_sept_hydropower-status-report.pdf
iha, 2021, https://assets-global.website-files.com/5f749e4b9399c80b5e421384/60c37321987070812596e26a_IHA20212405-status-report-02_LR.pdf

**Comment by ebbekyhl** [comment]
Duration is defined here https://github.com/PyPSA/powerplantmatching/blob/ae06ab50bd6ec2f778798c5eff256144de58f450/powerplantmatching/data.py#L420 

But this issue mentions that the 'StorageCapacity_MWh' attribute might not be very accurate: https://github.com/energy-modelling-toolkit/hydro-power-database/issues/1#issue-431861691

Furthermore, the 'Villarino Almendra' (id 487) might be the main source of error, with a power capacity of 851 MW and a duration of 3666 hours.

**Comment by FabianHofmann** [comment]
@ebbekyhl there was a bug in the aggregation of duration values (missing values distorted the weighted average computation). With the newest version of ppm, the capacities are at 9.05 TWh again. Where the missing 1 TWh comes from I cannot say atm... If this solves the initial issue, feel free to close it.

**Comment by ebbekyhl** [comment]
Thanks for checking up on this, @fneum. I will close this issue. My initial remark concerned whether 4 (or now 9) TWh was a realistic estimate of current PHS capacity. But this might more relate to the hydro-power-database by the JRC - and thus not a bug in powerplantmatching.

**Comment by FabianHofmann** [comment]
Sorry for not reading the initial issue properly again. You are right, this seems to be an issue with JRC, for example the largest storage reservoir are 

|      | Name                                       | Country   |   StorageCapacity_MWh |
|-----:|:-------------------------------------------|:----------|----------------------:|
| 2643 | Svartisen                                  | Norway    |           4.86983e+06 |
| 2385 | Saurdal                                    | Norway    |           3.19291e+06 |
| 2905 | Villarino Vllrino Almendra Villarino Spain | Spain     |           3.12e+06    |
| 2186 | Rana                                       | Norway    |           2.4474e+06  |
| 1339 | Kobbelv                                    | Norway    |           2.12101e+06 |


which seem to be too high I'd say.

**Comment by FabianHofmann** [comment]
thanks @martavp, I'll retag them as reservoirs then.
