### ISSUE TITLE
Dataset GEM_GGPT not working

### ISSUE THREAD

**Issue by davide-f** [PyPSA/powerplantmatching#76]
Hi!

The new contribution by GEM_GGPT is very interesting, but unfortunately it is not working.
The new feature is not in the config.yaml and hence it is not being tested in the ci.

As a confirmation, if we look at the followin lines, it is possible to notice that df is not defined if config is not None, which is usually the case.
https://github.com/PyPSA/powerplantmatching/blob/ae06ab50bd6ec2f778798c5eff256144de58f450/powerplantmatching/data.py#L1553-L1559

Moreover, I fear that the format of the file of the dataset has changed.

**Comment by pz-max** [comment]
@davide-f , I played a bit around here: https://github.com/max-parzen/powerplantmatching potentially fixing GEM_GGPT
I am quite unsure if the stats improved or not. It would be good to have a before -> after powerplant capacity comparison to always  track the impact of changes to the codebase. Let's catch up next week to test the GEM_GGPT changes :)
