### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by davide-f** [PyPSA/powerplantmatching#92]
I was wondering that after the last release in August, there have been several updates and it may be appropriate to release a new version, maybe (0.5.5?)

What do you think @FabianHofmann ?

That would help also us to use conda s package manager rather than installing it with pip

**Comment by FabianHofmann** [comment]
Just release the new version :)

**Comment by davide-f** [comment]
> Just released the new version :)

Thank you very much! :)
As the conda version is on, we'll include that official release into pypsa-earth, thank you!
Do you think it will be online in the next days?

**Comment by FabianHofmann** [comment]
likely tomorrow :)
